import type { Role } from '@/types';
export interface NavItem { label: string; href: string; icon: string; badge?: number; roles: Role[]; group?: string; }
export const NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard',     href: '/admin/dashboard',                      icon: 'LayoutDashboard', roles: ['ADMIN'],                              group: 'Overview' },
  { label: 'Dashboard',     href: '/manager/dashboard',                    icon: 'LayoutDashboard', roles: ['MANAGER'],                            group: 'Overview' },
  { label: 'My Tasks',      href: '/staff/dashboard',                      icon: 'ClipboardList',   roles: ['STAFF'],                              group: 'Overview' },
  { label: 'Portal',        href: '/customer/dashboard',                   icon: 'Home',            roles: ['CUSTOMER'],                           group: 'Overview' },
  { label: 'Work Orders',   href: '/maintenance/dashboard',                icon: 'Wrench',          roles: ['MAINTENANCE'],                        group: 'Overview' },
  { label: 'Kitchen',       href: '/chef/dashboard',                       icon: 'ChefHat',         roles: ['CHEF'],                               group: 'Overview' },
  { label: 'Rooms',         href: '/admin/dashboard/rooms',                icon: 'BedDouble',       roles: ['ADMIN', 'MANAGER'],                   group: 'Operations' },
  { label: 'Bookings',      href: '/admin/dashboard/bookings',             icon: 'Calendar',        roles: ['ADMIN', 'MANAGER'],                   group: 'Operations' },
  { label: 'Payments',      href: '/admin/dashboard/payments',             icon: 'CreditCard',      roles: ['ADMIN', 'MANAGER'],                   group: 'Operations' },
  { label: 'Staff',         href: '/admin/dashboard/staff',                icon: 'Users',           roles: ['ADMIN', 'MANAGER'],                   group: 'People' },
  { label: 'Users',         href: '/admin/dashboard/users',                icon: 'Shield',          roles: ['ADMIN'],                              group: 'People' },
  { label: 'Tasks',         href: '/staff/dashboard/tasks',                icon: 'ClipboardList',   roles: ['STAFF'],                              group: 'Work' },
  { label: 'Housekeeping',  href: '/staff/dashboard/housekeeping',         icon: 'Building2',       roles: ['STAFF', 'MAINTENANCE'],               group: 'Work' },
  { label: 'Food & Orders', href: '/admin/dashboard/food',                 icon: 'ChefHat',         roles: ['ADMIN', 'MANAGER'],                   group: 'Food' },
  { label: 'Orders',        href: '/chef/dashboard/orders',                icon: 'ShoppingBag',     roles: ['CHEF'],                               group: 'Food' },
  { label: 'Menu',          href: '/chef/dashboard/menu',                  icon: 'ChefHat',         roles: ['CHEF'],                               group: 'Food' },
  { label: 'Maintenance',   href: '/admin/dashboard/maintenance',          icon: 'Wrench',          roles: ['ADMIN', 'MANAGER'],                   group: 'Facilities' },
  { label: 'Requests',      href: '/maintenance/dashboard/requests',       icon: 'ClipboardList',   roles: ['MAINTENANCE'],                        group: 'Work' },
  { label: 'Inventory',     href: '/admin/dashboard/inventory',            icon: 'Package',         roles: ['ADMIN', 'MANAGER'],                   group: 'Facilities' },
  { label: 'My Bookings',   href: '/customer/dashboard/bookings',          icon: 'Calendar',        roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'Room Service',  href: '/customer/dashboard/food',              icon: 'ChefHat',         roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'Services',      href: '/customer/dashboard/services',          icon: 'Zap',             roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'My Reviews',    href: '/customer/dashboard/reviews',           icon: 'Star',            roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'Profile',       href: '/customer/dashboard/profile',           icon: 'Users',           roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'Reviews',       href: '/admin/dashboard/reviews',              icon: 'Star',            roles: ['ADMIN', 'MANAGER'],                   group: 'Insights' },
  { label: 'Services',      href: '/admin/dashboard/services',             icon: 'Zap',             roles: ['ADMIN', 'MANAGER'],                   group: 'Operations' },
  { label: 'Reports',       href: '/admin/dashboard/reports',              icon: 'BarChart3',       roles: ['ADMIN', 'MANAGER'],                   group: 'Insights' },
  { label: 'Notifications', href: '/admin/dashboard/notifications',        icon: 'Bell',            roles: ['ADMIN', 'MANAGER'],                   group: 'Insights' },
  { label: 'Notifications', href: '/customer/dashboard/notifications',     icon: 'Bell',            roles: ['CUSTOMER'],                           group: 'Guest' },
  { label: 'Notifications', href: '/staff/dashboard/notifications',        icon: 'Bell',            roles: ['STAFF', 'MAINTENANCE', 'CHEF'],       group: 'Work' },
  { label: 'System',        href: '/admin/dashboard/system',               icon: 'Settings',        roles: ['ADMIN'],                              group: 'System' },
];
